<div class="panel-body">
	<div class="col-sm-6">
		<div class="page-title">
			<div class="title_left">
				<h2>Recorrencias</h2>
			</div>
		</div>
		<table class="table">
			<thead>
				<tr>
					<th>Id</th>
					<th>Nome</th>
				</tr>
			</thead>
			<tbody>
				<?php
				if ($view_rec) :
					foreach ($view_rec as $rec) :
						?>
						<tr>
							<td><?php echo $rec->id ?></td>
							<td><?php echo $rec->nome ?></td>
						</tr>
						<?php
					endforeach;
				endif;
				?>
			</tbody>
		</table>
	</div>
	<div class="col-sm-6">
		<div class="page-title">
			<div class="title_left">
				<h2>Cadastro</h2>
			</div>
		</div>
		<?php
		$action = BASE . 'recurrence/cadastrar';
		$values = [
			'nome' => $this->request->post('nome')
		];
		Form::open('pagamento', $values, [
			'action' => $action,
			'enctype' => 'multipart/form-data',
			'style' => '',
			'prevent' => [
				'focus'
			]
		]);
		Form::Textbox(
			'Nome:',
			'nome',
			array(
				'required' => 1
			)
		);
		Form::Button('Salvar', 'submit', [
			'style' => 'width: 65%;float:  right;',
			'class' => 'btn-success'
		]);
		Form::close(false);
		?>
	</div>
</div>