<div class="panel-body">
  <form class="form-horizontal" action="<?php echo BASE; ?>cadastro/cadastrar" method="POST">
    <div class="form-group">
      <label for="name" class="col-sm-3 control-label">Nome:</label>
      <div class="col-sm-8">
        <input required type="text" class="form-control" id="name" name="name" placeholder="Nome Completo" value="<?php echo $this->request->post('name') ?>">
      </div>
    </div>
    <div class="form-group">
      <label for="email" class="col-sm-3 control-label">E-mail:</label>
      <div class="col-sm-8">
        <input required type="email" class="form-control" id="email" name="email" placeholder="seuemail@site.com.br" value="<?php echo $this->request->post('email') ?>">
      </div>
    </div>
    <div class="form-group">
      <label for="username" class="col-sm-3 control-label">Usuário:</label>
      <div class="col-sm-8">
        <input required type="text" class="form-control" id="username" name="username" placeholder="Seu usuário" value="<?php echo $this->request->post('username') ?>">
      </div>
    </div>
    <div class="form-group">
      <label for="password" class="col-sm-3 control-label">Senha:</label>
      <div class="col-sm-8">
        <input required type="password" class="form-control" id="password" name="password" placeholder="Sua senha">
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-3 col-sm-8">
        <button type="submit" class="btn btn-success">Cadastrar</button>
      </div>
    </div>
  </form>
</div>
