<div class="page-title">
	<div class="title_left">
		<h2>Diarias - UBER</h2>
	</div>
	<div class="title_right">
		<button id="addCustos" class="btn btn-info btn-lg" data-toggle="modal" data-target=".bd-example-modal-lg">
			Adicionar Diaria
		</button>
	</div>
</div>
<div class="clearfix"></div>
<div class="panel-body">
	<table class="table">
		<thead>
			<tr>
				<th>Data</th>
				<th>Ganhos Bruto</th>
				<th>Ganhos Liquido</th>
				<th>Custos do Dia</th>
				<th>KM Rodado</th>
				<th>Horas Online</th>
				<th>Viagens</th>
			</tr>
		</thead>
		<tbody>
			<?php
			if ($view_diarias) :
				foreach ($view_diarias as $diaria) :
					?>
					<tr>
						<td><?php echo $diaria->data ?></td>
						<td><?php echo $diaria->bruto ?></td>
						<td><?php echo $diaria->liquido ?></td>
						<td><?php echo $diaria->custos ?></td>
						<td><?php echo $diaria->km ?></td>
						<td><?php echo $diaria->horas ?></td>
						<td><?php echo $diaria->viagens ?></td>
					</tr>
					<?php
				endforeach;
			endif;
			?>
		</tbody>
	</table>
</div>
<div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title">Adicionar Diaria</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
				<p>*** FORM ***</p>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-primary">Salvar</button>
				<button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
			</div>
		</div>
	</div>
</div>