<script type="text/javascript">
	$(document).ready(function(){
		$('#optEmpresa').change(function(){
			$("#filtraEmpresa").submit();
		});
	});
</script>
<style type="text/css">
.btnPad a {
	width: 27%;
	float: left;
	margin: 0 3%;
}
.btnPad{
	width: 100px;
}
</style>
<div class="page-title">
	<div class="title_left" style="width: 25%">
		<h2>Lista de clientes</h2>
	</div>
	<div class="relatorioAtd">
		<?php
		$atendentes = User::find('all',array('conditions' => array('role_id = 2 AND status = 1')));
		foreach ($atendentes as $atd) {
			$aCobrar = Client::find('all', array('conditions' => array('cobrador = ?', $atd->id)));
			$aCobrarTotal = count($aCobrar);

			$cobrado = Call::find('all', array('conditions' => array('user_id = ? AND date_format(data_cad,\'%d/%m/%Y\') = ?', $atd->id, date('d/m/Y'))));
			$cobradoTotal = count($cobrado);
			?>
			<div class="cobradora">
				<p class="nome"><?php echo $atd->name; ?></p>
				<div class="resultados">
					<table width="100%">
						<tr>
							<td style="border-right:  1px solid #fff;">
								<h3><?php echo $aCobrarTotal; ?></h3>
								<p>A cobrar</p>
							</td>
							<td>
								<h3><?php echo $cobradoTotal; ?></h3>
								<p>Cobrado</p>
							</td>
						</tr>
					</table>
				</div>
			</div>
			<?php
		}
		?>
	</div>
	<div style="float:  right;padding-top: 10px;width: 15%">
		<?php
		if (isset($view_empresa) && $view_empresa != "") {
			$url = BASE.'cliente/cadastrar/'.$view_empresa;
		}else{
			$url = BASE.'cliente/cadastrar';
		}
		?>
		<a href="<?php echo $url ?>" style="float: left;" class="btn btn-info">
			ADICIONAR CLIENTE
		</a>
	</div>
</div>
<div class="clearfix"></div>
<div class="panel-body">
	<form method="POST" action="<?php echo BASE ?>cliente/enviarDivida" id="enviarDivida">
		<table class="table" id="tableFull">
			<thead>
				<tr>
					<th></th>
					<th>Empresa</th>
					<th>Nome</th>
					<th>CPF</th>
					<th width="110">Valor Dívida</th>
					<th width="110">Vl Atualizado</th>
					<th>Atds</th>
					<th>Cobradora / Status</th>
					<th></th>
				</tr>
			</thead>
			<tfoot>
				<td colspan="2">
					<?php
					$cobradores = User::find('all', array('conditions' => array('role_id = 2')));
					?>
					<select name="cobradora" class="form-control">
						<option>Selecione a Cobradora</option>
						<?php
						foreach ($cobradores as $cobrador) {
							echo '<option value="'.$cobrador->id.'">'.$cobrador->name.'</option>';
						}
						?>
					</select>
				</td>
				<td><input type="submit" class="btn btn-info" value="Enviar" style="margin: 0"></td>
				<td colspan="5">Enviar para cobrança</td>
			</tfoot>
			<tbody>
				<?php
				if ($view_clientes){
					foreach ($view_clientes as $cliente){
						$empresa = Company::find_by_id($cliente->companies_id);
						$dividas = Debt::find('all', array('conditions' => array('cliente_id = ?', $cliente->id)));
						$valorTotal = 0;
						$vlAtualizado = 0;
						foreach ($dividas as $divida) {
							$valorTotal = $valorTotal+$divida->valor;
							$vlAtualizado = $vlAtualizado+Debt::vlAtualizado($divida->valor, $divida->vencimento, $empresa->multa, $empresa->juros);
						}
						?>
						<tr class="<?php echo ClienteController::atd($cliente->id) ?>">
							<td><input type="checkbox" name="dividas[]" value="<?php echo $cliente->id ?>"></td>
							<td><?php echo $empresa->empresa ?></td>
							<td><?php echo $cliente->nome; ?></td>
							<td><?php echo $cliente->cpf ?></td>
							<td>R$ <?php echo number_format($valorTotal, 2, ",", ".") ?></td>
							<td>R$ <?php echo number_format($vlAtualizado, 2, ",", "."); ?></td>
							<td>
								<?php
								$atds = Call::find('all', array('conditions' => array('cliente_id = ?', $cliente->id)));
								echo count($atds);
								?>
							</td>
							<td style="width: 200px">
								<?php
								$atds = Call::find('all',array('conditions' => array('cliente_id = ?', $cliente->id), 'order' => 'data_cad desc'));
								if (!is_null($cliente->cobrador)) {
									if ($cliente->cobrador > 0) {
										$cobradora = User::find_by_id($cliente->cobrador);
										echo '<p class="cobrador">'.$cobradora->name.' <span>Atribuído</span></p>';
										if (count($atds) > 0) {
											echo '<p class="cobradorAnt">'.User::find_by_id($atds[0]->user_id)->name.' <span>Última Cobrança</span></p>';
										}
									}else{
										if (!is_null($cliente->status) && $cliente->status != "") {
											$status = State::find_by_id($cliente->status);
											echo $status->nome;
										}else{
											echo "Não atribuido";
											if (count($atds) > 0) {
												echo '<p class="cobradorAnt">'.User::find_by_id($atds[0]->user_id)->name.' <span>Última Cobrança</span></p>';
											}
										}
									}
								}else{
									if (!is_null($cliente->status)) {
										$status = State::find_by_id($cliente->status);
										echo @$status->nome;
									}else{
										echo "Não atribuido";
										if (count($atds) > 0) {
											echo '<p class="cobradorAnt">'.User::find_by_id($atds[0]->user_id)->name.' <span>Última Cobrança</span></p>';
										}
									}
								}
								?>
							</td>
							<td style="text-align: right;">
								<p class="btnPad">
									<a href="<?php echo BASE.'cliente/filtrar/'.$cliente->id ?>">
										<img class="img-responsive" src="<?php echo IMG; ?>icone-dividas.png" alt="Dividas">
									</a>
									<a href="<?php echo BASE.'cliente/editar/'.$cliente->id ?>">
										<img class="img-responsive" src="<?php echo IMG; ?>icone-editar.png" alt="editar">
									</a>
									<a href="<?php echo BASE.'cliente/excluir/'.$cliente->id ?>">
										<img class="img-responsive" src="<?php echo IMG; ?>icone-excluir.png" alt="editar">
									</a>
								</p>
							</td>
						</tr>
						<?php
					}
				}
				?>
			</tbody>
		</table>
	</form>
</div>