<?php
$empresa = Company::find_by_id($view_clientes->companies_id);
$dividas = Debt::find('all', array('conditions' => array('cliente_id = ?', $view_clientes->id), 'order' => 'data_cad desc'));
$atds = Call::find('all', array('conditions' => array('cliente_id = ?', $view_clientes->id), 'order' => 'data_cad desc'));

$valorTotal = 0;
$vlAtualizado = 0;
foreach ($dividas as $divida) {
	$valorTotal = $valorTotal+$divida->valor;
	$vlAtualizado = $vlAtualizado+Debt::vlAtualizado($divida->valor, $divida->vencimento, $empresa->multa, $empresa->juros);
}
?>
<div class="panel-body">
	<div class="row">
		<div class="col-md-8" style="margin-bottom: 20px;">
			<p><?php echo $empresa->empresa; ?></p>
			<h1><?php echo $view_clientes->nome; ?> <a href="<?php echo BASE ?>cliente/editar/<?php echo $view_clientes->id ?>"><img class="img-responsive" src="<?php echo IMG; ?>icone-editar.png" alt="editar" style="display: inline;width:  25px;margin-top: -20px;"></a></h1>
			<h2><?php echo $view_clientes->cpf; ?></h2>
		</div>
		<div class="col-md-4">
			<div class="row valorDivida">
				<div class="col-md-6">
					Valor Total:<br />
					<b>R$ <?php echo number_format($valorTotal, 2, ",", ".") ?></b>
				</div>
				<div class="col-md-6">
					Valor Atualizado:<br />
					<b>R$ <?php echo number_format($vlAtualizado, 2, ",", ".") ?></b>
				</div>
			</div>
			<div class="row">
				<div class="col-md-4" style="">
					<button type="button" class="btn btn-info btn-sm" data-toggle="modal" data-target="#modalAtd">
						ATENDIMENTO
					</button>
					<!-- Modal -->
					<div class="modal fade bd-example-modal-lg" id="modalAtd" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
						<div class="modal-dialog modal-lg" role="document">
							<div class="modal-content">
								<div class="modal-header">
									<?php
									$action = BASE . 'cliente/cadLog/'.$view_clientes->id;
									$values = [
										'vlNeg' => $this->request->post('vlNeg'),
										'obs' => $this->request->post('obs'),
										'status' => $this->request->post('status'),
										'telefones' => $view_clientes->telefones,
										'enderecos' => $view_clientes->enderecos,
										'protocolo' => $view_clientes->protocolo
									];
									Form::open('cadLog'.$view_clientes->id, $values, [
										'action' => $action,
										'view' => "Vertical",
										'name' => "atendimento",
										'enctype' => 'multipart/form-data',
										'prevent' => [
											'focus'
										]
									]);
									?>
									<div class="row-fluid">
										<div class="col-md-4">
											<h1 class="modal-title" id="exampleModalLongTitle" style="width:  100%;text-align: left;"><?php echo $view_clientes->nome; ?></h1>
											<h3 class="modal-title" id="exampleModalLongTitle" style="width:  100%;text-align: left;"><?php echo $view_clientes->cpf; ?></h3>
											<p class="modal-subtitulo">
												<?php echo $view_clientes->celular.' - '.$view_clientes->telefone.' - '.$view_clientes->recado; ?>
											</p>
										</div>
										<div class="col-md-8 vlAtd">
											<div class="row-fluid">
												<div class="col-md-12">
													<div class="info">
														<p class="nome">Valor Total:</p>
														<div class="resultados">
															<b>R$ <?php echo number_format($valorTotal, 2, ",", ".") ?></b>
														</div>
													</div>
													<div class="info">
														<p class="nome">Valor Atualizado:</p>
														<div class="resultados">
															<b>R$ <?php echo number_format($vlAtualizado, 2, ",", ".") ?></b>
														</div>
													</div>
												</div>
											</div>
											<?php
											if (!is_null($view_clientes->arquivos) && $view_clientes->arquivos != "") {
												?>
												<div class="row-fluid">
													<div class="col-md-12" style="margin-top: 15px;">
														<p style="margin-bottom: 0;">Anexos:</p>
														<?php
														$arquivos = json_decode($view_clientes->arquivos);

														$dir_path = BASE . 'public' . DS . 'uploads' . DS . 'clients' . DS . $view_clientes->id . DS;

														foreach ($arquivos as $arquivo) {
															echo '<a href="'.$dir_path.$arquivo->arquivo.'" class="btn btn-info" target="_blank">'.$arquivo->nome.'</a>';
														}
														?>
													</div>
												</div>
												<?php
											}
											?>
											<button type="button" class="close" data-dismiss="modal" aria-label="Close">
												<span aria-hidden="true">&times;</span>
											</button>
										</div>
									</div>
								</div>
								<div class="modal-body">
									<table class="table" id="tableAtd">
										<thead>
											<th>Valor</th>
											<th>Atendimento</th>
											<th>Status</th>
											<th>Data</th>
											<th>Atendente</th>
											<th></th>
										</thead>
										<tbody>
											<?php
											foreach ($atds as $atd) {
												?>
												<tr>
													<td>
														R$ <?php echo number_format($atd->vlneg, 2, ",", "."); ?>
													</td>
													<td><?php echo $atd->obs; ?></td>
													<td><?php echo State::find_by_id($atd->status_id)->nome; ?></td>
													<td><?php echo date("d/m/Y H:m", strtotime($atd->data_cad)); ?></td>
													<td><?php
													$atendente = User::find_by_id($atd->user_id);
													echo $atendente->name;
													?></td>
													<td>
														<?php
														$boleto = Payment::find(array('conditions' => array('atendimento_id = ?', $atd->id)));
														if (!is_null($boleto)) {
															?>
															<span class="btn btn-success">Boleto Gerado!</span>
															<?php
														}
														?>
													</td>
												</tr>
												<?php
											}
											?>
										</tbody>
									</table>
									<?php
									Form::close(false);
									?>
								</div>
								<div class="modal-footer">
									<button type="button" class="btn btn-secondary" data-dismiss="modal">
										Fechar
									</button>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="col-md-4">
					<a href="<?php echo BASE.'cliente/excluir/'.$view_clientes->id ?>/confirm" class="btn btn-lg btn-danger">Confirmar Exclusão</a>
				</div>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-8">
			<div class="page-title">
				<div class="title_left">
					<h2>Dívidas</h2>
				</div>
			</div>
			<table class="table" id="tableFullCobranca">
				<thead>
					<tr>
						<th></th>
						<th>Valor Original</th>
						<th>Valor Atualizado</th>
						<th>Dívida desde...</th>
						<th>Status</th>
						<th>Triagem</th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					<?php
					foreach ($dividas as $divida){
						$vlAtualizado = Debt::vlAtualizado($divida->valor, $divida->vencimento, $empresa->multa, $empresa->juros);
						?>
						<tr>
							<td>
								<input type="checkbox" id="dividaSelec" value="<?php echo $divida->id ?>" class="form-check-input" checked="true">
							</td>
							<td>R$ <?php echo number_format($divida->valor, 2, ",", "."); ?></td>
							<td>R$ <?php echo number_format($vlAtualizado, 2, ",", "."); ?></td>
							<td><?php echo date('d/m/Y', strtotime($divida->vencimento)); ?> <small><?php echo Debt::diasAtraso($divida->vencimento); ?> dias</small></td>
							<td><?php echo @State::find_by_id($divida->status_id)->nome; ?></td>
							<td><?php echo Types_debt::lista($divida->id); ?></td>
							<td>
								<?php if ($this->auth->getUserRole() == 'administrator') { ?>
									<span data-toggle="modal" data-target="#edit_<?php echo $divida->id ?>">
										<img class="img-responsive" src="<?php echo IMG; ?>icone-editar.png" alt="editar">
									</span>
								<?php } ?>
							</td>
						</tr>
						<div class="modal fade bd-example-modal-lg" id="edit_<?php echo $divida->id ?>" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
							<div class="modal-dialog modal-lg" role="document">
								<div class="modal-content">
									<div class="modal-header">
										<h3 class="modal-title" id="exampleModalLongTitle">
											Editar dívida de <?php echo $view_clientes->nome ?>
										</h3>
									</div>
									<div class="modal-body">
										<?php
										$action = BASE . 'cliente/editarDivida/'.$view_clientes->id.'/'.$divida->id;
										$values = [
											'valor' => $divida->valor,
											'vencimento' => date("Y-m-d", strtotime($divida->vencimento)),
											'obs' => $divida->obs
										];
										Form::open('cadLog'.$view_clientes->id, $values, [
											'action' => $action,
											'view' => "Vertical",
											'name' => "atendimento",
											'enctype' => 'multipart/form-data',
											'prevent' => [
												'focus'
											]
										]);
										?>
										<div class="row-fluid">
											<div class="col-md-12" style="text-align: right;margin-top: -10px;">
												<?php
												Form::Button('ATUALIZAR DÍVIDA', 'submit', [
													'class' => 'btn-success btnForm'
												]);
												?>
											</div>
										</div>
										<div class="row-fluid">
											<div class="col-md-4">
												<?php
												Form::Number(
													'Valor da Dívida:',
													'valor',
													array(
														'required' => 1,
														'min' => 0,
														'step' => '.01'
													)
												);
												?>
											</div>
											<div class="col-md-4">
												<?php
												Form::Date(
													'Vencimento:',
													'vencimento',
													array(
														'required' => 1
													)
												);
												?>
											</div>
											<div class="col-md-4">
												<?php
												if ($this->auth->getUserRole() == 'extrajudicial') {
													$status = State::busca(22);
												}elseif ($this->auth->getUserRole() == 'administrator') {
													if (is_null($view_clientes->status)) {
														$status = State::busca(0);
													}else{
														$status = State::busca($view_clientes->status);
													}
												}elseif ($this->auth->getUserRole() == 'juridico') {
													$status = State::busca(29);
												}else{
													$status = '';
												}
												$options = array();
												if (count($status) < 1) {
													$options[0] = 'Nenhum status informado, contate o admin';
												}else{
													foreach ($status as $stat) {
														$options[$stat->id] = $stat->nome;
													}
												}
												Form::Select(
													"Status",
													"status_id",
													$options,
													array(
														'value' => $divida->status_id,
														'required' => 1
													)
												);
												?>
											</div>
										</div>
										<div class="row-fluid">
											<div class="col-md-8">
												<?php
												Form::Textarea(
													'Observações:',
													'obs',
													array(
														'rows' => 6
													)
												);
												?>
											</div>
											<div class="col-md-4">
												<label style="float: left;width: 100%">Triagem</label>
												<?php
												$tipos = Type::all();
												$seq = Types_debt::listaArray($divida->id);
												$options = array();
												foreach ($tipos as $tipo) {
													$options[$tipo->id] = $tipo->tipo;
												}
												Form::Checkbox(
													'Tipo de dívida',
													'tipo',
													$options,
													array(
														'value' => $seq
													)
												);
												?>
											</div>
										</div>
										<?php
										Form::close(false);
										?>
									</div>
									<div class="modal-footer">
										<button type="button" class="btn btn-secondary" data-dismiss="modal">
											Fechar
										</button>
									</div>
								</div>
							</div>
						</div>
						<?php
					}
					?>
				</tbody>
			</table>
		</div>
		<div class="col-md-4 tableBoleto">
			<div class="page-title">
				<div class="title_left">
					<h2>Boletos</h2>
				</div>
			</div>
			<?php
			$boletosData = Payment::find('all', array('conditions' => array('cliente_id = ?', $view_clientes->id), 'order' => 'vencimento desc'));
			?>
			<table class="table" id="tableFull2">
				<thead>
					<tr>
						<th>Valor</th>
						<th>Vencimento</th>
						<th>Status</th>
					</tr>
				</thead>
				<tbody>
					<?php
					foreach ($boletosData as $boleto) {
						?>
						<tr>
							<td>
								<a href="<?php echo $boleto->boleto ?>" target="_blank">
									R$ <?php echo number_format($boleto->valor, 2, ",", ".") ?>
								</a>
							</td>
							<td><?php echo date("d/m/Y", strtotime($boleto->vencimento)) ?></td>
							<td><?php echo Payment::status($boleto->status) ?></td>
						</tr>
						<?php
					}
					?>
				</tbody>
			</table>
		</div>
	</div>
</div>
<script type="text/javascript">
	$(document).ready(function(e) {
		//Verifica todos os campos checados e manda para o campo qundo a página carrega
		dividas = [];
		$.each(($("#dividaSelec:checked")), function(index, obj){
			dividas.push(obj.value);
		});
		$('#dividas').val(dividas);

		//Verifica quais dívidas ficarem selecionadas após alteração e envia pro campo
		$("input[id=dividaSelec]").click(function(e) {
			dividas = [];
			$.each(($("#dividaSelec:checked")), function(index, obj){
				dividas.push(obj.value);
			});
			$('#dividas').val(dividas);
		});
	});

	function geraBoleto() {
		$("#boletos").show('slow');
		document.getElementById('tipo').value = "geraBoleto";
	}

	function add(id) {
		$('#boletoItem_'+id).show('slow');
	}
</script>