<div class="page-title">
  <div class="title_left">
    <h2>Cadastro de clientes</h2>
    <?php
    if (isset($view_empresa)) {
      $empresa = Company::find_by_id($view_empresa);
      echo '<p style="margin:0">'.$empresa->cnpj.'</p>';
      echo '<h3 style="margin:0">'.$empresa->empresa.'</h3>';
    }
    ?>
  </div>
</div>
<div class="clearfix"></div>
<div class="panel-body">
  <?php
  if (isset($view_cliente)) {
    $btn = 'Salvar';
    if (isset($view_empresa)) {
      $action = BASE . 'cliente/editar/'.$view_cliente->id.'/'.$view_empresa;
    }else{
      $action = BASE . 'cliente/editar/'.$view_cliente->id;
    }
    $values = [
      'cpf' => $view_cliente->cpf,
      'nome' => $view_cliente->nome,
      'email' => $view_cliente->email,
      'endereco' => $view_cliente->endereco,
      'celular' => $view_cliente->celular,
      'telefone' => $view_cliente->telefone,
      'recado' => $view_cliente->recado,
      'obs' => $view_cliente->obs,
      'idUserCliente' => $view_idCliente,
      'companies_id' => $view_cliente->companies_id,
      'enderecos' => $view_cliente->enderecos,
      'parentescos' => $view_cliente->parentescos,
      'status' => $view_cliente->status
    ];
  }else{
    $btn = 'Cadastrar';
    if (isset($view_empresa)) {
      $action = BASE . 'cliente/cadastrar/'.$view_empresa;
    }else{
      $action = BASE . 'cliente/cadastrar/';
    }
    $values = [
      'cpf' => $this->request->post('cpf'),
      'nome' => $this->request->post('nome'),
      'email' => $this->request->post('email'),
      'endereco' => $this->request->post('endereco'),
      'celular' => $this->request->post('celular'),
      'telefone' => $this->request->post('telefone'),
      'recado' => $this->request->post('recado'),
      'obs' => $this->request->post('obs'),
      'companies_id' => $this->request->post('companies_id'),
      'enderecos' => $this->request->post('enderecos'),
      'parentescos' => $this->request->post('parentescos'),
      'status' => $this->request->post('status')
    ];
  }
  Form::open('cadastrarcliente', $values, [
    'action' => $action,
    'enctype' => 'multipart/form-data',
    'prevent' => [
      'focus'
    ]
  ]
);
?>
<div class="row">
  <div class="col-sm-12" style="text-align: right;">
    <?php
    Form::Button($btn, 'submit', [
      'class' => 'btn-success btnForm',
      'id' => 'btnEnvia'
    ]);
    ?>
  </div>
</div>
<div class="row">
  <div class="col-sm-6">
    <?php
    Form::Textbox(
      'CPF / CNPJ:',
      'cpf',
      array(
        'required' => 1,
        'onkeypress' => 'mascaraMutuario(this,cpfCnpj)',
        'onblur' => 'clearTimeout()',
        'maxlength' => 18
      )
    );
    Form::Textbox(
      'Nome:',
      'nome',
      array(
        'required' => 1
      )
    );
    Form::Email(
      'Email:',
      'email'
    );
    Form::Phone(
      'Celular:',
      'celular',
      array(
        'data-inputmask' => "'mask' : '(99) 99999-9999'"
      )
    );
    Form::Phone(
      'Telefone:',
      'telefone',
      array(
        'data-inputmask' => "'mask' : '(99) 9999-9999'"
      )
    );
    Form::Phone(
      'Recado:',
      'recado',
      array(
        'data-inputmask' => "'mask' : '(99) 99999-9999'"
      )
    );
    Form::File(
      'Docs:',
      'arquivos[]',
      array(
        'multiple' => ""
      )
    );
    if (isset($view_cliente) && !is_null($view_cliente->arquivos) && $view_cliente->arquivos != "") {
      ?>
      <div class="form-group elem-arquivos[]">
        <label class="text-left-xs col-xs-12 col-md-4 control-label" for="arquivos[]">Anexos:</label>
        <div class="col-xs-12 col-md-8">
          <?php
          $arquivos = json_decode($view_cliente->arquivos);

          $dir_path = BASE . 'public' . DS . 'uploads' . DS . 'clients' . DS . $view_cliente->id . DS;
          foreach ($arquivos as $arquivo) {
            echo '<a href="'.$dir_path.$arquivo->arquivo.'" class="btn btn-info" target="_blank">'.$arquivo->nome.'</a>';
          }

          ?>
        </div>
      </div>
      <?php
    }
    ?>
  </div>
  <div class="col-sm-6">
    <?php
    Form::Textarea(
      'Endereço:',
      'endereco'
    );
    Form::Textarea(
      'Obs:',
      'obs'
    );
    if (!isset($view_empresa)) {
      $empresas = Company::all();
      $options = array(0=>'Selecione uma empresa abaixo');
      foreach ($empresas as $empresa) {
        $options[$empresa->id] = $empresa->empresa;
      }
      Form::Select(
        "Empresa",
        "companies_id",
        $options,
        array(
          'required' => 1,
          'class' => 'selectpicker',
          'data-live-search' => 'true'
        )
      );
    }else{
      Form::Hidden(
        'companies_id',
        $view_empresa
      );
    }
    if (isset($view_cliente)) {
      $users = User::all();
      $option2 = array(0=>'Selecione um usuário');
      foreach ($users as $value) {
        $option2[$value->id] = $value->name;
      }
      Form::Select(
        "Usuário",
        "idUserCliente",
        $option2
      );
    }
    if ($this->auth->getUserRole() == 'administrator') {
      $optStatusBase = State::find('all', array('conditions' => array('relacionamento = 0')));
      $optStatus = array();
      $optStatus[''] = 'Selecione um status';
      foreach ($optStatusBase as $value) {
        $optStatus[$value->id] = $value->nome;
      }
      Form::Select(
        "Status",
        "status",
        $optStatus
      );
    }else{
      if ($this->auth->getUserRole() == 'cobrança') {
        Form::Hidden(
          'companies_id',
          '20'
        );
      }
    }
    ?>
  </div>
</div>
<div class="row">
  <h4 style="float:  left;margin-right: 20px;">Higienização</h4>
  <?php
  if (isset($view_cliente)) {
    ?>
    <span class="btn btn-info" onclick="atualizarDados()">Atualizar Dados</span>
    <?php
  }
  ?>
</div>
<div class="row higi">
  <div class="col-sm-4">
    <label class="text-left-xs col-xs-12 col-md-4 control-label" for="enderecos" style="text-align:left;padding-left:0;">Telefones:</label>
    <div id="telefones" class="foneCad">
      <?php echo @$view_cliente->telefones; ?>
    </div>
    <input type="hidden" name="telefones" id="foneBd" value="<?php echo @$view_cliente->telefones; ?>">
  </div>
  <div class="col-sm-4">
    <?php
    Form::Textarea(
      'Endereços:',
      'enderecos',
      array(
        'readonly' => true,
        'style' => 'font-size: 90%'
      )
    );
    ?>
  </div>
  <div class="col-sm-4">
    <?php
    Form::Textarea(
      'Parentescos / Socios:',
      'parentescos',
      array(
        'readonly' => true,
        'style' => 'font-size: 90%'
      )
    );
    ?>
  </div>
</div>
<?php
Form::close(false);
?>
</div>
<script type="text/javascript">
  $("#cpf").blur(function() {
    var tamanho = $("#cpf").val().length;
    if (tamanho >= 14) {
      endereco = "";
      telefone = "";
      relacionamento = "";

      $("#telefones").html('Processando...');
      $("#enderecos").val('Processando...');
      $("#parentescos").val('Processando...');
      $("#btnEnvia").prop("disabled", true);

      if(tamanho == 14){
        $.ajax({
          method: "GET",
          url: "http://integracao.consultasprime.com/consultapessoafisica",
          data: { cnpjempresa: "19791503000150", usuario: "contato@websampa.com.br", senha: "DTJ!1607", cpf: $("#cpf").val() },
          crossDomain: true,
          dataType: 'jsonp'
        })
        .done(function( data ) {
          dados = data;
          dadosPfisica(data);
        })
        .fail(function( data ) {
          $("#telefones").html('Falha na requisição do ajax...');
          $("#enderecos").val('Falha na requisição do ajax...');
          $("#parentescos").val('Falha na requisição do ajax...');
          $("#btnEnvia").prop("disabled", false);
        });
      } else if(tamanho == 18){
        $.ajax({
          method: "GET",
          url: "http://integracao.consultasprime.com/consultapessoajuridica",
          data: { cnpjempresa: "19791503000150", usuario: "contato@websampa.com.br", senha: "DTJ!1607", cnpj: $("#cpf").val() },
          crossDomain: true,
          dataType: 'jsonp'
        })
        .done(function( data ) {
          dados = data;
          dadosPjuridica(data);
        })
        .fail(function( data ) {
          $("#telefones").html('Falha na requisição do ajax...');
          $("#enderecos").val('Falha na requisição do ajax...');
          $("#parentescos").val('Falha na requisição do ajax...');
          $("#btnEnvia").prop("disabled", false);
        });
      }else{
        $("#telefones").html('Verifique o campo CPF/CNPJ!');
        $("#enderecos").val('Verifique o campo CPF/CNPJ!');
        $("#parentescos").val('Verifique o campo CPF/CNPJ!');
        $("#btnEnvia").prop("disabled", true);
      }
    }
  });

  function atualizarDados() {
    var tamanho = $("#cpf").val().length;
    endereco = "";
    telefone = "";
    relacionamento = "";

    $("#telefones").html('Processando...');
    $("#enderecos").val('Processando...');
    $("#parentescos").val('Processando...');
    $("#btnEnvia").prop("disabled", true);
    if (tamanho == 14) {
      $.ajax({
        method: "GET",
        url: "http://integracao.consultasprime.com/consultapessoafisica",
        data: { cnpjempresa: "19791503000150", usuario: "contato@websampa.com.br", senha: "DTJ!1607", cpf: $("#cpf").val() },
        crossDomain: true,
        dataType: 'jsonp'
      })
      .done(function( data ) {
        dadosPfisica(data);
      })
      .fail(function( data ) {
        $("#telefones").html('Falha na requisição do ajax...');
        $("#enderecos").val('Falha na requisição do ajax...');
        $("#parentescos").val('Falha na requisição do ajax...');
        $("#btnEnvia").prop("disabled", false);
      });
    } else if (tamanho == 18) {
      $.ajax({
        method: "GET",
        url: "http://integracao.consultasprime.com/consultapessoajuridica",
        data: { cnpjempresa: "19791503000150", usuario: "contato@websampa.com.br", senha: "DTJ!1607", cnpj: $("#cpf").val() },
        crossDomain: true,
        dataType: 'jsonp'
      })
      .done(function( data ) {
        dadosPjuridica(data);
      })
      .fail(function( data ) {
        $("#telefones").html('Falha na requisição do ajax...');
        $("#enderecos").val('Falha na requisição do ajax...');
        $("#parentescos").val('Falha na requisição do ajax...');
        $("#btnEnvia").prop("disabled", false);
      });
    } else {
      $("#telefones").html('Verifique o campo CPF/CNPJ!');
      $("#enderecos").val('Verifique o campo CPF/CNPJ!');
      $("#parentescos").val('Verifique o campo CPF/CNPJ!');
      $("#btnEnvia").prop("disabled", true);
    }
  }

  function dadosPfisica(data) {
    if (data.prime.erro == 'false') {
    //Trata endereço
    $("#enderecos").text('');
    $.each(data.Enderecos.Ends, function (index, value) {
      $.each(value, function (idx, end) {
        if (idx == 'Bairro') {
          bairro = end
        }
        if (idx == 'CEP') {
          cep = end
        }
        if (idx == 'Cidade') {
          cid = end
        }
        if (idx == 'Logradouro') {
          $.each(end, function (idx2, end2) {
            if (idx2 == 'Nome') {
              rua = end2
            }
            if (idx2 == 'Numero') {
              numero = end2
            }
            if (idx2 == 'Complemento') {
              comp = end2
            }
          });
        }
        if (idx == 'UF') {
          uf = end
        }
      });
      endereco = endereco+rua+', '+numero+', '+comp+' '+bairro+'\n'+cid+' - '+uf+' - '+cep+'\n\n';
    });
    $("#enderecos").val(endereco);

    //Trata telefone
    $("#telefones").html('');
    $.each(data.Telefones.Fones, function (index, value) {
      $.each(value, function (idx, tell) {
        if (idx == 'DDD') {
          ddd = tell
        }
        if (idx == 'Numero') {
          numero = tell
        }
        if (idx == 'Tipo') {
          tipo = tell
        }
      });
      telefone += '<a href="https://api.whatsapp.com/send?phone=('+ddd+')'+numero+'&amp;text=Olá" target="_blank">('+ddd+')'+numero+'</a>';
    });
    $("#telefones").html(telefone);
    $("#foneBd").val(telefone);

    //Trata parentescos
    $("#parentescos").text('');
    $.each(data.ListaParentes.Parentes, function (index, value) {

      $.each(value, function (idx, relac) {
        if (idx == 'Relacionamento') {
          relacion = relac
        }
        if (idx == 'Cpf') {
          cpfRelac = relac
        }
        if (idx == 'Nome') {
          nomeRelac = relac
        }
      });

      fonesAux = '';
      relacionamento = relacionamento+cpfRelac+' - '+nomeRelac+' ('+relacion+')\n';
      /*
      $.ajax({
        method: "GET",
        url: "http://integracao.consultasprime.com/consultapessoafisica",
        data: { cnpjempresa: "19791503000150", usuario: "contato@websampa.com.br", senha: "DTJ!1607", cpf: cpfRelac },
        crossDomain: true,
        dataType: 'jsonp'
      }).done(function( data ) {
        if (data.Telefones.Fones != "undefined") {
          $.each(data.Telefones.Fones, function (index, value) {
            $.each(value, function (idx, tell) {
              if (idx == 'DDD') {
                ddd = tell
              }
              if (idx == 'Numero') {
                numero = tell
              }
              if (idx == 'Tipo') {
                tipo = tell
              }
            });
            if (fonesAux != '') {
              fonesAux = fonesAux+' - ';
            }
            fonesAux += '('+ddd+')'+numero;
          });
        }
      }).fail(function( data ) {
        console.log('Erro '+data);
      });
      relacionamento = relacionamento+'\nFones: '+fonesAux+'\n';
      */
    });
    $.each(data.ListaSociedades.Sociedades, function (index, value) {
      $.each(value, function (idx, socied) {
        if (idx == 'CNPJ') {
          cnpj = socied
        }
        if (idx == 'RazaoSocial') {
          nome = socied
        }
      });
      relacionamento = relacionamento+cnpj+' - '+nome+' (Socio)\n';
    });
    $("#parentescos").val(relacionamento);
    $("#btnEnvia").prop("disabled", false);
  }else{
    $("#enderecos").val('Erro na pesquisa de dados,\nVerifique os erros abaixo!\n'+data.prime.mensagem);
    $("#telefones").html('Erro na pesquisa de dados,\nVerifique os erros abaixo!\n'+data.prime.mensagem);
    $("#parentescos").val('Erro na pesquisa de dados,\nVerifique os erros abaixo!\n'+data.prime.mensagem);
    $("#btnEnvia").prop("disabled", false);
  }
}

function dadosPjuridica(data) {
  if (data.prime.erro == 'false') {
    //Trata endereço
    $("#enderecos").text('');
    $.each(data.Enderecos.Ends, function (index, value) {
      $.each(value, function (idx, end) {
        if (idx == 'Bairro') {
          bairro = end
        }
        if (idx == 'CEP') {
          cep = end
        }
        if (idx == 'Cidade') {
          cid = end
        }
        if (idx == 'Logradouro') {
          $.each(end, function (idx2, end2) {
            if (idx2 == 'Nome') {
              rua = end2
            }
            if (idx2 == 'Numero') {
              numero = end2
            }
            if (idx2 == 'Complemento') {
              comp = end2
            }
          });
        }
        if (idx == 'UF') {
          uf = end
        }
      });
      endereco = endereco+rua+', '+numero+', '+comp+' '+bairro+'\n'+cid+' - '+uf+' - '+cep+'\n\n';
    });
    $("#enderecos").val(endereco);

    //Trata telefone
    $("#telefones").html('');
    $.each(data.Telefones.Fones, function (index, value) {
      $.each(value, function (idx, tell) {
        if (idx == 'DDD') {
          ddd = tell
        }
        if (idx == 'Numero') {
          numero = tell
        }
        if (idx == 'Tipo') {
          tipo = tell
        }
      });
      telefone += '<a href="https://api.whatsapp.com/send?phone=('+ddd+')'+numero+'&amp;text=Olá" target="_blank">('+ddd+')'+numero+'</a>';
    });
    $("#telefones").html(telefone);
    $("#foneBd").val(telefone);

    //Trata parentescos
    $("#parentescos").text('');
    $.each(data.ListaQuadroSocial.QuadroSocial, function (index, value) {
      $.each(value, function (idx, relac) {
        if (idx == 'Documento') {
          cpfRelac = relac
        }
        if (idx == 'NomeRazaoSocialSocio') {
          nomeRelac = relac
        }
      });
      relacionamento += cpfRelac+' - '+nomeRelac+' (Socios)\n';
    });
    $("#parentescos").val(relacionamento);
    $("#btnEnvia").prop("disabled", false);
  }else{
    $("#enderecos").val('Erro na pesquisa de dados,\nVerifique os erros abaixo!\n'+data.prime.mensagem);
    $("#telefones").html('Erro na pesquisa de dados,\nVerifique os erros abaixo!\n'+data.prime.mensagem);
    $("#parentescos").val('Erro na pesquisa de dados,\nVerifique os erros abaixo!\n'+data.prime.mensagem);
    $("#btnEnvia").prop("disabled", false);
  }
}

function mascaraMutuario(o,f){
  v_obj=o
  v_fun=f
  setTimeout('execmascara()',1)
}
function execmascara(){
  v_obj.value=v_fun(v_obj.value)
}
function cpfCnpj(v){
  v=v.replace(/\D/g,"")
  if (v.length <= 11) {
    v=v.replace(/(\d{3})(\d)/,"$1.$2")
    v=v.replace(/(\d{3})(\d)/,"$1.$2")
    v=v.replace(/(\d{3})(\d{1,2})$/,"$1-$2")
  } else {
    v=v.replace(/^(\d{2})(\d)/,"$1.$2")
    v=v.replace(/^(\d{2})\.(\d{3})(\d)/,"$1.$2.$3")
    v=v.replace(/\.(\d{3})(\d)/,".$1/$2")
    v=v.replace(/(\d{4})(\d)/,"$1-$2")
  }
  return v
}
</script>