<script type="text/javascript">
	$(document).ready(function(){
		$('#optEmpresa').change(function(){
			$("#filtraEmpresa").submit();
		});
	});
</script>
<div class="page-title">
	<div class="title_left">
		<h2>Lista de clientes</h2>
	</div>
	<div style="float:  right;padding-top: 10px;width: 55%;">
		<?php if ($this->auth->getUserRole() != 'cobrança' && $this->auth->getUserRole() != 'cliente' && $this->auth->getUserRole() != 'extrajudicial' && $this->auth->getUserRole() != 'juridico') { ?>
			<a href="<?php echo BASE ?>cliente/cadastrar" class="btn btn-info">ADICIONAR CLIENTE</a>
		<?php } ?>
		<?php
		if ($this->auth->getUserRole() != 'cobrança' && $this->auth->getUserRole() != 'extrajudicial' && $this->auth->getUserRole() != 'juridico') {
			?>
			<form action="<?php echo BASE ?>cliente/empresa" id="filtraEmpresa" method="POST">
				<select name="empresa" id="optEmpresa" class="form-control">
					<option>Selecione um Empresa</option>
					<?php
					$empresas = Company::all();
					foreach ($empresas as $empresa) {
						echo '<option value="'.$empresa->id.'">'.$empresa->empresa.'</option>';
					}
					?>
				</select>
			</form>
			<?php
		}else{
			?>
			<form action="<?php echo BASE ?>cliente/busca" id="filtraEmpresa" method="POST" style="width: 100%;margin: 0;">
				<div class="form-group">
					<input type="text" name="nome" class="form-control" id="buscaCliente" placeholder="Informe nome" style="float: left;width: 45%;margin-right: 2%">
					<input type="text" name="cpf" onkeypress="mascaraMutuario(this,cpfCnpj)" onblur="clearTimeout()" maxlength="18" id="cpf" class="form-control" placeholder="Informe o CPF" style="float: left;width: 30%;margin-right: 2%;">
					<button type="submit" name="" style="" class="btn-success btn btn-primary" id="btnEnvia" style="width: 20%;float: right;">Buscar Cliente</button>
				</div>
			</form>
			<?php
		}
		?>
	</div>
</div>
<div class="clearfix"></div>
<div class="panel-body">
	<table class="table" id="tableFullCobranca">
		<thead>
			<tr>
				<th>Empresa</th>
				<th>Nome</th>
				<th>CPF</th>
				<th width="110">Valor Dívida</th>
				<th width="110">Vl Atualizado</th>
				<th>Atd</th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<?php
			if ($view_clientes){
				foreach ($view_clientes as $cliente){
					$empresa = Company::find_by_id($cliente->companies_id);
					$dividas = Debt::find('all', array('conditions' => array('cliente_id = ?', $cliente->id)));
					$valorTotal = 0;
					$vlAtualizado = 0;
					foreach ($dividas as $divida) {
						$valorTotal = $valorTotal+$divida->valor;
						$vlAtualizado = $vlAtualizado+Debt::vlAtualizado($divida->valor, $divida->vencimento, $empresa->multa, $empresa->juros);
					}
					?>
					<tr class="<?php echo ClienteController::atd($cliente->id) ?>">
						<td><?php echo $empresa->empresa ?></td>
						<td><?php echo $cliente->nome; ?></td>
						<td><?php echo $cliente->cpf ?></td>
						<td>R$ <?php echo number_format($valorTotal, 2, ",", ".") ?></td>
						<td>R$ <?php echo number_format($vlAtualizado, 2, ",", "."); ?></td>
						<td>
							<?php
							$atds = Call::find('all', array('conditions' => array('cliente_id = ?', $cliente->id)));
							echo count($atds);
							?>
						</td>
						<td style="text-align: right;">
							<p class="btnPad">
								<a href="<?php echo BASE.'cliente/filtrar/'.$cliente->id ?>" class="unico">
									<img class="img-responsive" src="<?php echo IMG; ?>icone-dividas.png" alt="Dividas">
								</a>
							</p>
						</td>
					</tr>
					<?php
				}
			}
			?>
		</tbody>
	</table>
</div>
<script type="text/javascript">
	function mascaraMutuario(o,f){
		v_obj=o
		v_fun=f
		setTimeout('execmascara()',1)
	}
	function execmascara(){
		v_obj.value=v_fun(v_obj.value)
	}
	function cpfCnpj(v){
		v=v.replace(/\D/g,"")
		if (v.length <= 11) {
			v=v.replace(/(\d{3})(\d)/,"$1.$2")
			v=v.replace(/(\d{3})(\d)/,"$1.$2")
			v=v.replace(/(\d{3})(\d{1,2})$/,"$1-$2")
		} else {
			v=v.replace(/^(\d{2})(\d)/,"$1.$2")
			v=v.replace(/^(\d{2})\.(\d{3})(\d)/,"$1.$2.$3")
			v=v.replace(/\.(\d{3})(\d)/,".$1/$2")
			v=v.replace(/(\d{4})(\d)/,"$1-$2")
		}
		return v
	}
</script>