<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="panel panel-custom">
      <div class="panel-heading">
        <a id="logo" href="<?php echo BASE; ?>">
          <img class="img-responsive" src="<?php echo IMG; ?>hxphp-logo.png" alt="">
        </a> <br>
        <?php echo (isset($this->menu) ? $this->menu : ''); ?>
      </div>
      <div class="panel-body">
        <?php echo (isset($this->alert) ? $this->alert : ''); ?>
      </div>
    </div>
  </div>
</div>
