<div class="panel-body">
  <?php echo (isset($this->alert) ? $this->alert : ''); ?>
  <form class="form-horizontal" method="POST" action="<?php echo BASE; ?>recuperar/solicitar/">
    <div class="form-group">
      <label for="email" class="col-sm-3 control-label">E-mail:</label>
      <div class="col-sm-8">
        <input type="email" class="form-control" id="email" name="email" placeholder="Forneça seu e-mail" value="<?php echo $this->request->post('email'); ?>">
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-3 col-sm-8">
        <button type="submit" class="btn btn-success">Enviar link de redefinição</button>
      </div>
    </div>
  </form>
</div>