<div class="panel-body">
  <?php echo (isset($this->alert) ? $this->alert : ''); ?>
  <form class="form-horizontal" method="POST" action="<?php echo BASE; ?>recuperar/alterar-senha/<?php echo $view_token; ?>">
    <div class="form-group">
      <label for="password" class="col-sm-3 control-label">Nova senha:</label>
      <div class="col-sm-8">
        <input type="password" class="form-control" id="password" name="password" placeholder="Informe sua nova senha">
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-3 col-sm-8">
        <button type="submit" class="btn btn-success">Alterar minha senha</button>
      </div>
    </div>
  </form>
</div>