<div class="page-title">
	<div class="title_left">
		<h2>Lista de Contas</h2>
	</div>
	<div class="title_right">
		<button id="addCustos" class="btn btn-info btn-lg" data-toggle="modal" data-target=".bd-example-modal-lg">
			Adicionar Conta
		</button>
	</div>
</div>
<div class="clearfix"></div>
<div class="panel-body">
	<table class="table">
		<thead>
			<tr>
				<th>Tipo</th>
				<th>Onde</th>
				<th>Cliente/Fornecedor</th>
				<th>Data Cadastro</th>
				<th>Valor</th>
				<th>Categoria</th>
				<th>Recorrencia</th>
				<th>Vencimento</th>
				<th>Pago</th>
				<th>Status</th>
			</tr>
		</thead>
		<tbody>
			<?php
			if ($view_contas) :
				foreach ($view_contas as $conta) :
					?>
					<tr>
						<td><?php echo $conta->tipo ?></td>
						<td><?php echo $conta->pagamento ?></td>
						<td><?php echo $conta->cliente ?></td>
						<td><?php echo $conta->data ?></td>
						<td><?php echo $conta->valor ?></td>
						<td><?php echo $conta->categoria ?></td>
						<td><?php echo $conta->recorrencia ?></td>
						<td><?php echo $conta->vencimento ?></td>
						<td><?php echo $conta->data_pagamento ?></td>
						<td><?php echo $conta->status ?></td>
					</tr>
					<?php
				endforeach;
			endif;
			?>
		</tbody>
	</table>
</div>
<div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title">Adicionar Conta</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
				<p>*** FORM ***</p>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-primary">Salvar</button>
				<button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
			</div>
		</div>
	</div>
</div>