<div class="page-title">
	<div class="title_left">
		<h2>Custos - UBER</h2>
	</div>
	<div class="title_right">
		<button id="addCustos" class="btn btn-info btn-lg" data-toggle="modal" data-target=".bd-example-modal-lg">
			Adicionar Custo
		</button>
	</div>
</div>
<div class="clearfix"></div>
<div class="panel-body">
	<table class="table">
		<thead>
			<tr>
				<th>Id</th>
				<th>Nome</th>
				<th>Diaria Uber</th>
				<th>Fornecedor</th>
				<th>Vencimento</th>
				<th>Status</th>
			</tr>
		</thead>
		<tbody>
			<?php
			if ($view_custos) :
				foreach ($view_custos as $custo) :
					?>
					<tr>
						<td><?php echo $custo->id ?></td>
						<td><?php echo $custo->diaria_id ?></td>
						<td><?php echo $custo->nome ?></td>
						<td><?php echo $custo->fornecedor_id ?></td>
						<td><?php echo $custo->vencimento ?></td>
						<td><?php echo $custo->status ?></td>
					</tr>
					<?php
				endforeach;
			endif;
			?>
		</tbody>
	</table>
</div>
<div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title">Adicionar Custos</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
				<p>*** FORM ***</p>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-primary">Salvar</button>
				<button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
			</div>
		</div>
	</div>
</div>