<div class="panel-body">
    <?php
    $this->partial('message', array(
        'msg' => 'Uhull! Você instalou e configurou o HXPHP Framework com sucesso!'
    ));
    ?>
    <p>
        Agora acesse a <a class="btn btn-success btn-xs" href="http://www.hxtutors.com.br/curso/dominando-o-hxphp-framework/" title="Acesse o curso completo sobre HXPHP" target="_blank">área de membros</a> e assista ao nosso curso oficial para dominar completamente esta poderosa ferramenta.
    </p>
</div>