<div class="panel-body">
	<div class="col-sm-6">
		<div class="page-title">
			<div class="title_left">
				<h2>Tipo de Pagamentos</h2>
			</div>
		</div>
		<table class="table">
			<thead>
				<tr>
					<th>Id</th>
					<th>Nome</th>
				</tr>
			</thead>
			<tbody>
				<?php
				if ($view_pagamentos) :
					foreach ($view_pagamentos as $pagamento) :
						?>
						<tr>
							<td><?php echo $pagamento->id ?></td>
							<td><?php echo $pagamento->nome ?></td>
						</tr>
						<?php
					endforeach;
				endif;
				?>
			</tbody>
		</table>
	</div>
	<div class="col-sm-6">
		<div class="page-title">
			<div class="title_left">
				<h2>Cadastro</h2>
			</div>
		</div>
		<?php
		if (isset($view_pagamento)) {
			$action = BASE.'payment/editar/'.$view_pagamento->id;
			$values = [
				'nome' => $view_pagamento->nome,
				'dados' => $view_pagamento->dados
			];
		}else{
			$action = BASE . 'payment/cadastrar';
			$values = [
				'nome' => $this->request->post('nome'),
				'dados' => $this->request->post('dados')
			];
		}
		Form::open('pagamento', $values, [
			'action' => $action,
			'enctype' => 'multipart/form-data',
			'style' => '',
			'prevent' => [
				'focus'
			]
		]);
		Form::Textbox(
			'Nome:',
			'nome',
			array(
				'required' => 1
			)
		);
		Form::Textarea(
			'Dados:',
			'dados',
			array(
				'required' => 1
			)
		);
		Form::Button('Salvar', 'submit', [
			'style' => 'width: 65%;float:  right;',
			'class' => 'btn-success'
		]);
		Form::close(false);
		?>
	</div>
</div>