<div class="page-title">
  <div class="title_left">
    <h2>Cadastro de empresa</h2>
  </div>
</div>
<div class="clearfix"></div>
<div class="panel-body cadEmpresa">
  <?php
  $idUserEmpresa = "";
  if (isset($view_emp)) {
    $action = BASE . 'empresa/editar/'.$view_emp->id;
    $documentos = Document::find(array('conditions' => array('companies_id = ?', $view_emp->id)));
    if (!is_null($documentos)) {
      $bdDocs = array(
        'contrato_assinado' => $documentos->contrato_assinado,
        'contrato_social' => $documentos->contrato_social,
        'comprovante_endereco' => $documentos->comprovante_endereco,
        'conta_bancaria' => $documentos->conta_bancaria,
        'procuracao' => $documentos->procuracao
      );
      foreach ($bdDocs as $key => $value) {
        if ($value == 0) {
          unset($bdDocs[$key]);
        }else{
          $bdDocs[$key] = $key;
        }
      }
    }
    $idUserEmpresa = $view_emp->iduserempresa;
    $values = [
      'cnpj' => $view_emp->cnpj,
      'gerente' => $view_emp->gerente,
      'idUserEmpresa' => $idUserEmpresa,
      'empresa' => $view_emp->empresa,
      'contato' => $view_emp->contato,
      'email' => $view_emp->email,
      'endereco' => $view_emp->endereco,
      'telefone' => $view_emp->telefone,
      'celular' => $view_emp->celular,
      'taxa' => $view_emp->taxa,
      'multa' => $view_emp->multa,
      'juros' => $view_emp->juros,
      'contrato' => $view_emp->contrato,
      'contrato_social' => $view_emp->contrato_social,
      'cartao_cnpj' => $view_emp->cartao_cnpj,
      'comprovante_endereco' => $view_emp->comprovante_endereco,
      'banco' => $view_emp->banco,
      'tipo_conta' => $view_emp->tipo_conta,
      'agencia' => $view_emp->agencia,
      'conta' => $view_emp->conta,
      'autorizacao_terceiro' => $view_emp->autorizacao_terceiro,
      'documentos' => @$bdDocs
    ];
    $btn = 'Editar Empresa';
  }else{
    $action = BASE . 'empresa/cadastrar/';
    $values = [
      'cnpj' => $this->request->post('cnpj'),
      'gerente' => $this->request->post('gerente'),
      'empresa' => $this->request->post('empresa'),
      'contato' => $this->request->post('contato'),
      'email' => $this->request->post('email'),
      'endereco' => $this->request->post('endereco'),
      'telefone' => $this->request->post('telefone'),
      'celular' => $this->request->post('celular'),
      'multa' => $this->request->post('multa'),
      'juros' => $this->request->post('juros'),
      'taxa' => $this->request->post('taxa'),
      'contrato' => $this->request->post('contrato'),
      'contrato_social' => $this->request->post('contrato_social'),
      'cartao_cnpj' => $this->request->post('cartao_cnpj'),
      'comprovante_endereco' => $this->request->post('comprovante_endereco'),
      'banco' => $this->request->post('banco'),
      'tipo_conta' => $this->request->post('tipo_conta'),
      'agencia' => $this->request->post('agencia'),
      'conta' => $this->request->post('conta'),
      'autorizacao_terceiro' => $this->request->post('autorizacao_terceiro')
    ];
    $btn = 'Cadastrar Empresa';
  }
  Form::open('cadastrarempresa', $values, [
    'action' => $action,
    'enctype' => 'multipart/form-data',
    "view" => "Inline",
    'prevent' => ['focus']
  ]);
  ?>
  <div class="row">
    <h4>Dados da Empresa</h4>
    <div class="row-fluid">
      <div class="col-sm-4">
        <?php
        Form::Textbox(
          'Nome:',
          'empresa',
          array(
            'required' => 1
          )
        );
        ?>
      </div>
      <div class="col-sm-4">
        <?php
        Form::Textbox(
          'CNPJ/CPF:',
          'cnpj',
          array(
            'required' => 1,
            'data-inputmask' => "'mask': '99.999.999/9999-99'"
          )
        );
        ?>
      </div>
      <div class="col-sm-4">
        <?php
        Form::Email(
          'E-mail:',
          'email',
          array(
            'required' => 1
          )
        );
        ?>
      </div>
    </div>
    <div class="row-fluid">
      <div class="col-sm-3">
        <?php
        $gerentes = User::all();
        $optGerente = array();
        foreach ($gerentes as $gerente) {
          $optGerente[$gerente->id] = $gerente->name;
        }
        Form::Select(
          "Gerente de Conta",
          "gerente",
          $optGerente,
          array(
            'class' => 'selectpicker',
            'data-live-search' => 'true'
          )
        );
        ?>
      </div>
      <div class="col-sm-3">
        <?php
        Form::Textbox(
          'Contato:',
          'contato',
          array(
            'required' => 1
          )
        );
        ?>
      </div>
      <div class="col-sm-3">
        <?php
        Form::Textbox(
          'Telefone:',
          'telefone',
          array(
            'required' => 1,
            'data-inputmask' => "'mask' : '(99) 9999-9999'"
          )
        );
        ?>
      </div>
      <div class="col-sm-3">
        <?php
        Form::Textbox(
          'Celular:',
          'celular',
          array(
            'required' => 1,
            'data-inputmask' => "'mask' : '(99) 99999-9999'"
          )
        );
        ?>
      </div>
    </div>
    <div class="row-fluid">
      <div class="col-sm-12">
        <?php
        Form::Textarea(
          'Endereço:',
          'endereco',
          array(
            'required' => 1
          )
        );
        ?>
      </div>
    </div>
  </div>

  <div class="row">
    <h4>Taxas</h4>
    <div class="col-sm-4">
      <?php
      Form::Textbox(
        'Taxa DivCred:',
        'taxa',
        array(
          'required' => 1,
          'value' => 20
        )
      );
      ?>
    </div>
    <div class="col-sm-4">
      <?php
      Form::Textbox(
        'Multa:',
        'multa',
        array(
          'required' => 1
        )
      );
      ?>
    </div>
    <div class="col-sm-4">
      <?php
      Form::Textbox(
        'Juros:',
        'juros',
        array(
          'required' => 1
        )
      );
      ?>
    </div>
  </div>
  <div class="row">
    <h4>Documentos</h4>
    <div class="row-fluid">
      <div class="col-sm-5">
        <div class="row-fluid">
          <?php
          Form::File(
            'Contrato Assinado:',
            'contrato'
          );
          ?>
        </div>
        <div class="row-fluid">
          <?php
          Form::File(
            'Contrato Social:',
            'contrato_social'
          );
          ?>
        </div>
        <div class="row-fluid">
          <?php
          Form::File(
            'Cartão CNPJ:',
            'cartao_cnpj'
          );
          ?>
        </div>
        <div class="row-fluid">
          <?php
          Form::File(
            'Comprovante Endereço:',
            'comprovante_endereco'
          );
          ?>
        </div>
      </div>
      <div style="float:  left;width: 400px;">
        <?php
        $docs = array(
          'contrato_assinado' => 'Contrato Assinado',
          'contrato_social' => 'Contrato Social',
          'comprovante_endereco' => 'Comprovante de Endereço',
          'procuracao' => 'Assinatura da Procuração',
          'conta_bancaria' => 'Conta Bancária'
        );
        Form::Checkbox(
          'Documentos enviados',
          'documentos',
          $docs
        );
        ?>
      </div>
    </div>
  </div>
  <div class="row">
    <h4>Banco</h4>
    <div class="row-fluid">
      <div class="col-sm-3">
        <?php
        $tipo = array('Corrente' => 'Corrente', 'Poupança' => 'Poupança');
        Form::Select(
          "Tipo de conta",
          "tipo_conta",
          $tipo,
          $attributes = null
        );
        ?>
      </div>
      <div class="col-sm-3">
        <?php
        $bancos = Bank::all();
        $optBanco = array();
        foreach ($bancos as $banco) {
          $optBanco[$banco->id] = $banco->nome;
        }
        Form::Select(
          "Banco",
          "banco",
          $optBanco,
          array(
            'class' => 'selectpicker',
            'data-live-search' => 'true'
          )
        );
        ?>
      </div>
      <div class="col-sm-3">
        <?php
        Form::Textbox(
          'Agência:',
          'agencia'
        );
        ?>
      </div>
      <div class="col-sm-3">
        <?php
        Form::Textbox(
          'Conta:',
          'conta'
        );
        ?>
      </div>
    </div>
    <div class="row-fluid">
      <div class="col-sm-6">
        <?php
        Form::File(
          'Carta de autorização:',
          'autorizacao_terceiro'
        );
        ?>
      </div>
      <div class="col-sm-6">
        <?php
        if ($idUserEmpresa != "") {
          Form::Select(
            "Usuário",
            "iduserempresa",
            $view_option2
          );
        }
        ?>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12" style="text-align: center;">
      <?php
      Form::Button($btn, 'submit', [
        'style' => 'width: 400px;margin: 30px 0px;',
        'class' => 'btn-success'
      ]);
      ?>
    </div>
  </div>
  <?php
  Form::close(false);
  ?>
</div>