<div class="row-fluid">
	<div class="page-title" style="margin-bottom: 15px;">
		<div class="title_left">
			<h2>Lista de Empresas</h2>
		</div>
		<div style="float:  right;padding-top: 10px;width: 15%">
			<a href="<?php echo BASE ?>empresa/cadastrar" style="float: left;" class="btn btn-info">
				ADICIONAR EMPRESA
			</a>
		</div>
	</div>
	<div class="row tile_count relatBoleto">
		<div class="tile_stats_count">
			<span class="count_top"><i class="fa fa-user"></i> Total de Clientes</span>
			<div class="count">
				<?php echo $view_relatorio->totalClientes ?>
			</div>
			<span class="count_bottom">Total de clientes cadastrados</span>
		</div>
		<div class="tile_stats_count">
			<span class="count_top"><i class="fa fa-list-alt"></i> Total de Dívidas</span>
			<div class="count">
				<?php echo $view_relatorio->totalDebitos ?>
			</div>
			<span class="count_bottom">Total de dívidas cadastradas</span>
		</div>
		<div class="tile_stats_count">
			<span class="count_top"><i class="fa fa-clipboard"></i> Boletos Negociados</span>
			<div class="count blue">
				<?php echo $view_relatorio->total ?>
			</div>
			<span class="count_bottom">Total de boletos gerados</span>
		</div>
		<div class="tile_stats_count">
			<span class="count_top"><i class="fa fa-clipboard"></i> Boletos Pagos</span>
			<div class="count green">
				<?php echo $view_relatorio->pagos ?>
			</div>
			<span class="count_bottom">Total de boletos pagos</span>
		</div>
		<div class="tile_stats_count">
			<span class="count_top"><i class="fa fa-clipboard"></i> Boletos Vencidos</span>
			<div class="count red">
				<?php echo $view_relatorio->vencidos ?>
			</div>
			<span class="count_bottom">Total de boletos vencidos</span>
		</div>
	</div>
	<table class="table" id="tableFullEmpresa">
		<thead>
			<tr>
				<th></th>
				<th>Empresa</th>
				<th>Documentos Faltantes</th>
				<th>Boletos Emitidos</th>
				<th>Boletos Pagos</th>
				<th>Clientes</th>
				<th>Total Dívidas</th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<?php
			if ($view_empresa){
				foreach ($view_empresa as $emp){
					$clientes = Client::busca_cliente($emp->id);
					$gerente = User::find_by_id($emp->gerente);
					$docs = Document::find(array('conditions' => array('companies_id = ?', $emp->id)));
					if (isset($gerente->cor)) {
						$bg = $gerente->cor;
					}else{
						$bg = '#fff';
					}

					$vlTotalDevendo = 0;
					$vlTotalPago = 0;
					$totalDividas = 0;
					foreach ($clientes as $cliente) {
						$pags = Payment::find('all', array('conditions' => array('cliente_id = ?', $cliente->id)));
						if (count($pags)>0) {
							foreach ($pags as $pag) {
								if ($pag->status == 'RECEIVED') {
									$vlTotalPago += $pag->valor;
								}else{
									$vlTotalDevendo += $pag->valor;
								}
							}
						}

						$dividas = Debt::find('all', array('conditions' => array('cliente_id = ?', $cliente->id)));
						$totalDividas = $totalDividas+count($dividas);
					}
					?>
					<tr>
						<td>
							<div class="corEmp" style="background: <?php echo $bg ?>"></div>
						</td>
						<td>
							<small><?php echo $emp->cnpj ?></small>
							<p><?php echo $emp->empresa ?></p>
						</td>
						<td><?php if ($docs) { echo Document::printDoc($docs); } ?></td>
						<td>
							<?php
							echo 'R$ '.number_format($vlTotalDevendo, 2, ",", ".");
							?>
						</td>
						<td>
							<?php
							echo 'R$ '.number_format($vlTotalPago, 2, ",", ".");
							?>
						</td>
						<td>
							<?php echo count($clientes); ?>
						</td>
						<td>
							<?php
							echo $totalDividas;
							?>
						</td>
						<td style="width:  100px;">
							<a href="<?php echo BASE.'cliente/empresa/'.$emp->id ?>" style="float:  left;width: 30%;margin-right: 2.5%;">
								<img class="img-responsive" src="<?php echo IMG; ?>icone-cliente.png" alt="cliente">
							</a>
							<?php
							if ($this->auth->getUserRole() == 'administrator') {
								?>
								<a href="<?php echo BASE.'empresa/editar/'.$emp->id ?>" style="float: left;width: 30%;margin-right: 2.5%;">
									<img class="img-responsive" src="<?php echo IMG; ?>icone-editar.png" alt="editar">
								</a>
								<a href="<?php echo BASE.'empresa/excluir/'.$emp->id ?>" style="float: left;width: 30%;">
									<img class="img-responsive" src="<?php echo IMG; ?>icone-excluir.png" alt="excluir">
								</a>
								<?php
							}
							?>
						</td>
					</tr>
					<?php
				}
			}
			?>
		</tbody>
	</table>
</div>

<!-- FastClick -->
<script src="<?php echo BOWER; ?>vendors/fastclick/lib/fastclick.js"></script>
<!-- NProgress -->
<script src="<?php echo BOWER; ?>vendors/nprogress/nprogress.js"></script>
<!-- Chart.js -->
<script src="<?php echo BOWER; ?>vendors/Chart.js/dist/Chart.min.js"></script>
<!-- gauge.js -->
<script src="<?php echo BOWER; ?>vendors/gauge.js/dist/gauge.min.js"></script>
<!-- bootstrap-progressbar -->
<script src="<?php echo BOWER; ?>vendors/bootstrap-progressbar/bootstrap-progressbar.min.js"></script>
<!-- iCheck -->
<script src="<?php echo BOWER; ?>vendors/iCheck/icheck.min.js"></script>
<!-- Skycons -->
<script src="<?php echo BOWER; ?>vendors/skycons/skycons.js"></script>
<!-- Flot -->
<script src="<?php echo BOWER; ?>vendors/Flot/jquery.flot.js"></script>
<script src="<?php echo BOWER; ?>vendors/Flot/jquery.flot.pie.js"></script>
<script src="<?php echo BOWER; ?>vendors/Flot/jquery.flot.time.js"></script>
<script src="<?php echo BOWER; ?>vendors/Flot/jquery.flot.stack.js"></script>
<script src="<?php echo BOWER; ?>vendors/Flot/jquery.flot.resize.js"></script>
<!-- Flot plugins -->
<script src="<?php echo BOWER; ?>vendors/flot.orderbars/js/jquery.flot.orderBars.js"></script>
<script src="<?php echo BOWER; ?>vendors/flot-spline/js/jquery.flot.spline.min.js"></script>
<script src="<?php echo BOWER; ?>vendors/flot.curvedlines/curvedLines.js"></script>
<!-- DateJS -->
<script src="<?php echo BOWER; ?>vendors/DateJS/build/date.js"></script>
<!-- JQVMap -->
<script src="<?php echo BOWER; ?>vendors/jqvmap/dist/jquery.vmap.js"></script>
<script src="<?php echo BOWER; ?>vendors/jqvmap/dist/maps/jquery.vmap.world.js"></script>
<script src="<?php echo BOWER; ?>vendors/jqvmap/examples/js/jquery.vmap.sampledata.js"></script>
<!-- bootstrap-daterangepicker -->
<script src="<?php echo BOWER; ?>vendors/moment/min/moment.min.js"></script>
<script src="<?php echo BOWER; ?>vendors/bootstrap-daterangepicker/daterangepicker.js"></script>