<div class="login_wrapper">
  <div class="animate form login_form">
    <?php echo(isset($this->alert)?$this->alert:''); ?>
    <section class="login_content">
      <form class="form-horizontal" action="<?php echo BASE; ?>login/logar" method="POST">
        <h1>Login</h1>
        <div class="form-group">
          <label for="username" class="col-sm-3 control-label">Usuário:</label>
          <div class="col-sm-8">
            <input type="text" class="form-control" id="username" name="username" value="<?php echo $this->request->post('username') ?>" placeholder="Seu usuário">
          </div>
        </div>
        <div class="form-group">
          <label for="password" class="col-sm-3 control-label">Senha:</label>
          <div class="col-sm-8">
            <input type="password" class="form-control" id="password" name="password" placeholder="Sua senha">
          </div>
        </div>
        <div class="">
          <button type="submit" class="btn btn-default submit">Entrar</button>
          <a href="<?php echo BASE; ?>recuperar" class="reset_pass">Esqueci minha senha</a>
        </div>
        <div class="clearfix"></div>
        <div class="separator"></div>
      </form>
    </section>
  </div>
</div>