<div class="page-title">
	<div class="title_left" style="margin-bottom: 15px;">
		<h2>Lista de usuários</h2>
	</div>
	<div style="float:  right;padding-top: 10px;width: 15%">
		<a href="<?php echo BASE ?>cadastro" style="float: left;" class="btn btn-info">
			ADICIONAR USUÁRIO
		</a>
	</div>
</div>
<div class="clearfix"></div>
<div class="panel-body">
	<table class="table" id="tableFull">
		<thead>
			<tr>
				<th>Nome</th>
				<th>E-mail</th>
				<th>Nível</th>
				<th>Ações</th>
			</tr>
		</thead>
		<tbody>
			<?php
			if ($view_users) :
				foreach ($view_users as $user) :
					?>
					<tr>
						<td><?php echo $user->name ?> (<?php echo $user->username ?>)</td>
						<td><?php echo $user->email ?></td>
						<td><?php echo $user->role->role; ?></td>
						<td>
							<p class="iconesUser">
								<a href="<?php echo BASE.'cadastro/editar/'.$user->id ?>" class="">
									<img class="img-responsive" src="<?php echo IMG; ?>icone-editar.png" alt="editar" title="Editar">
								</a>
								<?php
								if ($user->status === 0) {
									?>
									<a href="<?php echo BASE.'usuarios/desbloquear/'.$user->id ?>" class="">
										<img class="img-responsive" src="<?php echo IMG; ?>icone-bloqueado.png" alt="Bloqueado" title="Bloqueado">
									</a>
									<?php
								}else{
									?>
									<a href="<?php echo BASE.'usuarios/bloquear/'.$user->id ?>" class="">
										<img class="img-responsive" src="<?php echo IMG; ?>icone-desbloqueado.png" alt="Desbloqueado" title="Desbloqueado">
									</a>
									<?php
								}
								?>
								<a href="<?php echo BASE.'usuarios/excluir/'.$user->id ?>" class="">
									<img class="img-responsive" src="<?php echo IMG; ?>icone-excluir.png" alt="excluir" title="Excluir">
								</a>
							</p>
						</td>
					</tr>
					<?php
				endforeach;
			endif;
			?>
		</tbody>
	</table>
</div>