<div class="panel-body">
	<div class="col-sm-8">
		<div class="page-title">
			<div class="title_left">
				<h2>Usuários</h2>
			</div>
		</div>
		<table class="table">
			<thead>
				<tr>
					<th>Nome</th>
					<th>E-mail</th>
					<th>Login</th>
					<th>Ações</th>
				</tr>
			</thead>
			<tbody>
				<?php
				if ($view_users) :
					foreach ($view_users as $user) :
						?>
						<tr>
							<td><?php echo $user->name ?></td>
							<td><?php echo $user->email ?></td>
							<td><?php echo $user->username ?></td>
							<td>
								<?php
								if ($user->status === 0) {
									?>
									<a href="<?php echo BASE.'usuarios/desbloquear/'.$user->id ?>" class="btn btn-xs btn-success">
										<i class="fa fa-pencil"></i> Desbloquear
									</a>
									<?php
								}else{
									?>
									<a href="<?php echo BASE.'usuarios/bloquear/'.$user->id ?>" class="btn btn-xs btn-warning">
										<i class="fa fa-pencil"></i> Bloquear
									</a>
									<?php
								}
								?>
								<a href="<?php echo BASE.'usuarios/excluir/'.$user->id ?>" class="btn btn-xs btn-danger">
									<i class="fa fa-pencil"></i> Excluir
								</a>
							</td>
						</tr>
						<?php
					endforeach;
				endif;
				?>
			</tbody>
		</table>
	</div>
	<div class="col-sm-4">
		<div class="page-title">
			<div class="title_left">
				<h2>Cadastro</h2>
			</div>
		</div>
		<?php
		if (isset($view_usuario)) {
			$action = BASE . 'usuarios/editar/'.$view_usuario->id;
			$values = [
				'name' => $view_usuario->name,
				'email' => $view_usuario->email,
				'username' => $view_usuario->username,
				'password' => $view_usuario->password,
				'role' => $view_usuario->role
			];
		}else{
			$action = BASE . 'usuarios/cadastrar';
			$values = [
				'name' => $this->request->post('name'),
				'email' => $this->request->post('email'),
				'username' => $this->request->post('username'),
				'password' => $this->request->post('password'),
				'role' => $this->request->post('role')
			];
		}
		Form::open('usuarios', $values, [
			'action' => $action,
			'enctype' => 'multipart/form-data',
			'style' => '',
			'prevent' => [
				'focus'
			]
		]);
		Form::Textbox(
			'Nome:',
			'name',
			array(
				'required' => 1
			)
		);
		Form::Email(
			'E-mail:',
			'email',
			array(
				'required' => 1
			)
		);
		Form::Textbox(
			'Usuário:',
			'username',
			array(
				'required' => 1
			)
		);
		Form::Password(
			'Senha:',
			'password',
			array(
				'required' => 1
			)
		);
		$roles = Role::all();
		?>
		<div class="form-group elem-role_id">
			<label class="text-left-xs col-xs-12 col-md-4 control-label" for="role_id">
				<span class="required">* </span>Nível
			</label>
			<div class="col-xs-12 col-md-8">
				<select name="role_id" required="" id="role_id" class="form-control c-select">
					<option value="Selecione o nível">
						Selecione o nível
					</option>
					<?php
					foreach ($roles as $roleOpt) {
						?>
						<option value="<?php echo $roleOpt->id ?>">
							<?php echo $roleOpt->role ?>
						</option>
						<?php
					}
					?>
				</select>
			</div>
		</div>
		<?php
		Form::Button('Salvar', 'submit', [
			'style' => 'width: 65%;float:  right;',
			'class' => 'btn-success'
		]);
		Form::close(false);
		?>
	</div>
</div>