</div>
<!-- /page content -->

<!-- footer content -->
<footer>
	<div class="row">
		<div class="col-md10 col-md-offset-2 text-center">
			<a href="https://www.websampa.com.br/?ref=123" target="_blank" title="WebSampa Publicidades &amp; Sistemas Web">
				<img src="https://websampa.com.br/images/banners/copy.php/?ref=123" alt="Copy Websampa">
			</a>
		</div>
	</div>
	<div class="clearfix"></div>
</footer>
<!-- /footer content -->
</div>
</div>
<!-- Custom Theme Scripts -->
<script src="<?php echo BOWER; ?>build/js/custom.js"></script>
<!-- jquery.inputmask -->
<script src="<?php echo BOWER; ?>vendors/jquery.inputmask/dist/min/jquery.inputmask.bundle.min.js"></script>
</body>